# Generated by Django 2.2 on 2019-07-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
