# Generated by Django 2.2 on 2019-07-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_team_group_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='group_no',
            new_name='team_group_no',
        ),
    ]
