# Generated by Django 2.2 on 2019-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_auto_20190717_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=20, unique=True)),
                ('league', models.CharField(default='zjb', max_length=100)),
                ('league_year', models.CharField(default='2019', max_length=10)),
                ('game_level', models.CharField(max_length=10)),
                ('game_group', models.CharField(max_length=10)),
                ('game_date', models.DateField(blank=True)),
                ('game_start_time', models.TimeField(blank=True)),
                ('game_end_time', models.TimeField(blank=True)),
                ('game_court', models.CharField(max_length=50)),
                ('team_a_score', models.IntegerField(blank=True, null=True)),
                ('team_b_score', models.IntegerField(blank=True, null=True)),
                ('court_address', models.CharField(max_length=100)),
                ('game_complete', models.BooleanField(default=False)),
                ('team_a', models.ForeignKey(on_delete='CASCADE', related_name='team_a', to='basketball.Team', to_field='team_id')),
                ('team_b', models.ForeignKey(on_delete='CASCADE', related_name='team_b', to='basketball.Team', to_field='team_id')),
            ],
        ),
    ]
