# Generated by Django 2.2 on 2019-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_auto_20190729_0557'),
    ]

    operations = [
        
    ]
