# Generated by Django 2.2 on 2019-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_auto_20190729_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(default='zjb', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='league_year',
            field=models.CharField(default='2019', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='team_nick_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
