# Generated by Django 2.2 on 2019-07-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_auto_20190729_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_a_group_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b_group_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.CharField(default='zjb', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_a',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b',
            field=models.CharField(default='', max_length=50),
        ),
    ]
