# Generated by Django 2.2 on 2019-07-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0007_auto_20190729_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='league_year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
