# Generated by Django 2.2 on 2019-07-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0008_auto_20190729_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_a_group_no',
            field=models.CharField(default='', max_length=10, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b_group_no',
            field=models.CharField(default='', max_length=10, verbose_name='Group'),
        ),
    ]
