# Generated by Django 2.2 on 2019-07-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0009_auto_20190729_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('r', 'Regular'), ('p', 'Playoff')], default='r', max_length=1),
        ),
    ]
