# Generated by Django 2.2 on 2019-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0010_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_rank',
            field=models.CharField(default='', max_length=2),
        ),
    ]
