# Generated by Django 2.2 on 2019-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0011_team_team_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
