# Generated by Django 2.2 on 2019-08-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0012_auto_20190804_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_rank',
        ),
    ]
