# Generated by Django 2.2 on 2019-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0016_auto_20190804_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_credit',
            field=models.IntegerField(blank=True, null=True, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
